"""Twin experiments (§7): gradient-based calibration + variational DA.

Synthetic observations are generated by the model with known controls, then
recovered by minimizing the misfit. Confirms identifiability of the machinery:
  - parameter calibration (Emiss)
  - initial-state DA (temperature offset)
  - joint estimation (Emiss + state offset simultaneously)
Free-running twin (obs forcing off) so the surface temperature depends on the
controls being estimated.
"""

import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.run_no_coupling import build_model, RSP_SRC  # noqa: E402

pytest.importorskip("jax")
pytest.importorskip("optax")
import jax.numpy as jnp  # noqa: E402
from droad import jax_model as jm  # noqa: E402
from droad.assimilate import fit  # noqa: E402


def _setup(n=200):
    sys.path.insert(0, str(RSP_SRC))
    m, objs = build_model()
    mi, mo, phy, g, s, a, coup, st, cpm, _ = objs
    base = {"Poro1": phy.Poro1, "Poro2": phy.Poro2, "vsh1": phy.vsh1, "vsh2": phy.vsh2,
            "Emiss": phy.Emiss, "SB_const": phy.SB_const, "VK": phy.VK_Const,
            "logUstar": phy.logUstar, "logCond": phy.logCond, "logMom": phy.logMom,
            "logHeat": phy.logHeat, "ZRefT": phy.ZRefT, "Grav": phy.Grav,
            "LVap": phy.LVap, "LFus": phy.LFus}
    day = {"NightOn": st.NightOn, "NightOff": st.NightOff, "CalmLimDay": st.CalmLimDay,
           "CalmLimNgt": st.CalmLimNgt, "TrfFricDay": st.TrfFricDay, "TrfFricNgt": st.TrfFricNgt}
    hours = np.array([t.hour for t in mi.time[:n]], float)
    is_night = ((hours >= st.NightOn) | (hours <= st.NightOff))
    static = {"NLayers": st.NLayers, "DTSecs": st.DTSecs,
              "WCont": jnp.array(g.WCont, float), "CC": jnp.array(g.CC, float),
              "ZDpth": jnp.array(g.ZDpth, float), "DyK": jnp.array(g.DyK, float),
              "DyC": jnp.array(g.DyC, float), "day": day, "Albedo": g.Albedo}
    forc = {"Tair": jnp.array(mi.Tair[:n], float), "VZ": jnp.array(mi.VZ[:n], float),
            "Rhz": jnp.array(mi.Rhz[:n], float), "SW": jnp.array(mi.SW[:n], float),
            "LW": jnp.array(mi.LW[:n], float), "is_night": jnp.array(is_night),
            "mask": jnp.zeros(n, bool), "obs": jnp.zeros(n)}   # twin: no obs forcing
    x0 = (jnp.array(g.Tmp, float), jnp.array(g.TmpNw, float), jnp.float64(a.BLCond))
    w = jnp.ones(n)
    return base, static, forc, x0, w


def test_recover_emiss():
    base, static, forc, x0, w = _setup()
    true = 0.92
    obs = jm.dry_rollout({**base, "Emiss": true}, x0, forc, static)

    def loss(e):
        return jm.loss({**base, "Emiss": e}, x0, forc, obs, w, static)

    est, hist = fit(loss, jnp.float64(0.85), steps=300, lr=0.01)
    assert float(est) == pytest.approx(true, abs=1e-4)
    assert hist[-1] < hist[0] * 1e-6


def _offset_x0(x0, off):
    Tmp = x0[0].at[1:5].add(off)
    TmpNw = x0[1].at[1:5].add(off)
    return (Tmp, TmpNw, x0[2])


def test_recover_initial_state_offset():
    base, static, forc, x0, w = _setup()
    true_off = 3.0
    obs = jm.dry_rollout(base, _offset_x0(x0, true_off), forc, static)

    def loss(off):
        return jm.loss(base, _offset_x0(x0, off), forc, obs, w, static)

    est, hist = fit(loss, jnp.float64(0.0), steps=300, lr=0.1)
    assert float(est) == pytest.approx(true_off, abs=1e-2)


def test_joint_recover_param_and_state():
    base, static, forc, x0, w = _setup()
    true = {"Emiss": 0.92, "off": 2.0}
    obs = jm.dry_rollout({**base, "Emiss": true["Emiss"]},
                         _offset_x0(x0, true["off"]), forc, static)

    def loss(c):
        return jm.loss({**base, "Emiss": c["Emiss"]}, _offset_x0(x0, c["off"]),
                       forc, obs, w, static)

    est, hist = fit(loss, {"Emiss": jnp.float64(0.85), "off": jnp.float64(0.0)},
                    steps=500, lr=0.02)
    assert float(est["Emiss"]) == pytest.approx(true["Emiss"], abs=2e-3)
    assert float(est["off"]) == pytest.approx(true["off"], abs=5e-2)
